sudo: false
dist: trusty

language: node_js

cache:
  yarn: true

node_js:
- 'lts/*'

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH=$HOME/.yarn/bin:$PATH

script:
- yarn run lint
- yarn run test
